import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import { logDev, setToStorage } from '../utils'

export default function Home() {
  const router = useRouter();
  logDev('urlParams', router.asPath )
  setToStorage('urlParams', router.asPath)
  if (router.asPath  !== '/') {
    router.push(router.asPath )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Link href='/signup/'>
          Signup
        </Link>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
